### ISSUE TITLE
Register as a charity in Scotland

### ISSUE THREAD

**Issue by silky** [FixPlanet/org#2]
See: https://www.gov.uk/setting-up-charity

**Comment by silky** [comment]
This will probably involve such items as:

- [x] Formalise a constitution
- [ ] Outline the process for receiving additional monies

**Comment by silky** [comment]
David might know a bit about this; I'll ask him.

**Comment by silky** [comment]
Apparently there are different rules for Scottish charities - https://www.oscr.org.uk/becoming-a-charity/

**Comment by marcosh** [comment]
I guess it makes sense to ask someone who knows more about the legal implication of being a charity (or some other kinf of institution). In the oscr website they mention that https://ciof.org.uk/about-us/our-work-in-the-nations/scotland could help

**Comment by silky** [comment]
Some progress on this one:

- It looks like it's a "straightforward" matter to register a charity in scotland
- The main requirement is for 3 trustees (now: @silky @gacafe and @marcosh ) and some governance documentation

Relevant reading:

- https://www.oscr.org.uk/becoming-a-charity/becoming-a-scio/
- https://www.oscr.org.uk/managing-a-charity/faqs/
- https://scvo.scot/support/setting-up-a-charity

Reference charities:

Through some other slack communities, I found this website - https://www.protect.earth/ - and they have their governance document public - https://static1.squarespace.com/static/5f9323e965b0950d66514484/t/5fbaf666e8de8f008859aef2/1606088294991/Protect+Earth+Constitution+-+Approved+171120.pdf

The advice from them was that using a standard template made it easy for the office to approve them; so I think that's what we will do as well.

Next tasks here are:

- [x] Complete the reading of all the background
- [x] Put together a candidate consitution/governance document
- [x] Get sign-off from the trustees
- [x] Register it?!

**Comment by silky** [comment]
Looks like this is the place to begin the process - I'll start it next week.

https://status.oscr.org.uk/

**Comment by silky** [comment]
i'm closing this now as it's done; i'll make a new issue for dealing with any of the feedback we here from the application.
