### ISSUE TITLE
Solicit committee feedback on payout strategy

### ISSUE THREAD

**Issue by silky** [FixPlanet/org#3]
See: https://github.com/FixPlanet/org/blob/main/README.md#payout-strategy

Ideas:

- 50% start, 50% at the completion of final milestone
- 50% start, 50% at mid-way point
- ???

**Comment by marcosh** [comment]
I agree that having 3 payments, one at the beginning, one at the half and one at the end (release of some artefact) would be the best strategy

**Comment by silky** [comment]
potential plan:

- 40%
- 30%
- 30%

**Comment by silky** [comment]
Done; this is codified here: https://github.com/FixPlanet/org#payout-strategy
